TRAIN:
  ENABLE: True
  DATASET: echonet
  BATCH_SIZE: 32
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: '' #"/scratch/st-puranga-1/users/MohammadMahdi/Workspace/timesformerM/TimeSformer/outputdirpatch28/checkpoints/checkpoint_epoch_00054.pyth" #"/scratch/st-puranga-1/users/MohammadMahdi/Workspace/timesformerM/TimeSformer/outputdirdepth8/checkpoints/checkpoint_epoch_00053.pyth"#/scratch/st-puranga-1/users/MohammadMahdi/Workspace/timesformerM/TimeSformer/checkpoints/checkpoint_epoch_00016.pyth"
  FINETUNE: False
DATA:
  PATH_TO_DATA_DIR: ./path/to/echonet/
  length: 32
  SAMPLING_RATE: 32
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 112
  TEST_CROP_SIZE: 112
  INPUT_CHANNEL_NUM: [3]
  root: None
  split: "train"
  target_type: "EF"
  mean: [32.260647, 32.223927, 32.203083] 
  std: [48.50121, 48.47852, 48.446346]
  period: 2
  max_length: 250
  clips: 1
  pad: None
  noise: None
  target_transform: None
  external_test_location: None
  NUM_FRAMES: 32
TIMESFORMER:
  ATTENTION_TYPE: 'divided_space_time'
SOLVER:
  BASE_LR: 0.0001
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 45, 80]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 120
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: vit_base_patch16_224
  NUM_CLASSES: 1
  ARCH: vit
  LOSS_FUNC: mse_loss
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: echonet
  BATCH_SIZE: 4
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 3
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
TENSORBOARD: 
  PREDICTIONS_PATH: "/scratch/st-puranga-1/users/MohammadMahdi/Workspace/timesformerM/TimeSformer/outputslog_original_sgd/" #/scratch/st-puranga-1/users/MohammadMahdi/Workspace/timesformerM/TimeSformer/outputslog/" #"/scratch/st-puranga-1/users/MohammadMahdi/Workspace/timesformerM/TimeSformer/outputslogdepth8/"
  LOG_DIR: "/scratch/st-puranga-1/users/MohammadMahdi/Workspace/timesformerM/TimeSformer/outputslog_original_sgd/" #"/scratch/st-puranga-1/users/MohammadMahdi/Workspace/timesformerM/TimeSformer/outputslog/" #"/scratch/st-puranga-1/users/MohammadMahdi/Workspace/timesformerM/TimeSformer/outputslogdirdepth8/"
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: "/scratch/st-puranga-1/users/MohammadMahdi/Workspace/timesformerM/TimeSformer/outputsdir_original_sgd/" #"scratch/st-puranga-1/users/MohammadMahdi/Workspace/timesformerM/TimeSformer/outputdirpatch28/" #"/scratch/st-puranga-1/users/MohammadMahdi/Workspace/timesformerM/TimeSformer/outputdirdepth8"
